#Strings and Number Methods

In [ ]:
#string formatting
fname= "Anirudh"
lname = "Singh"

print("My first name is - {}, and last name is - {}.".format(fname, lname))

My first name is - Anirudh, and last name is - Singh.


In [ ]:
fname= "Anirudh"
lname = "Singh"

print("My first name is - {1}, and last name is - {0}.".format(fname, lname))

My first name is - Singh, and last name is - Anirudh.


In [ ]:
a = 10
id(a)  # Shows the location of a

10751144

In [ ]:
a=int(5)
b=int(10)
print("",b//a)

 2


###Number methods

In [ ]:
import math

In [ ]:
math.fabs(-54)

54.0

In [ ]:
math.log()

In [ ]:
math.log10()

In [ ]:
pow()

In [ ]:
sqrt(4)

In [ ]:
math.sin()
math.hypot()
math.modf(5.5)

(0.5, 5.0)

In [ ]:
max(3,4,5)

5

In [ ]:
ls = [3,4,5]
max(ls)

5

#Lists

In [ ]:
#Strings are immutable
ls = "Anirudh"
ls[0]

'A'

In [ ]:
lst = list((1,2,3,4,5)) #list(1,2,3,4,5) gives error
type(lst)

list

In [ ]:
lst.append()

In [ ]:
lst.insert(2,'a')
lst

[1, 2, 'a', 'a', 'a', 3, 4, 5]

In [ ]:
ls_2 = [1,2,3,4,5]
ls_2.extend([6,7])
ls_2

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
print(ls_2*3)

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]


In [ ]:
ls_3 = [1,2,3,4]
ls_3.pop(1)
ls_3

[1, 3, 4]

#Sets


*Set is unordered(sorted) <br>
cannot change a specific element directly (no indexing)

In [ ]:
print(type({}), type({1}))

<class 'dict'> <class 'set'>


In [ ]:
ls_01 = [1,1,2,2,3,3]
set(ls_01)

{1, 2, 3}

In [ ]:
#Defining an empty set
set_var = set()
print(set_var)
print(type(set_var))

set()
<class 'set'>


In [ ]:
set_var = {1,2,3,4}
set_var

{1, 2, 3, 4}

In [ ]:
#set_var[1] # Gives error because set is unscriptable
for i in set_var:
  print(i)       # But is it iterable

1
2
3
4


In [ ]:
set_1 = set([1,2,4])
set_1.add(3)
set_1

{1, 2, 3, 4}

In [ ]:
set_01 = {1,2,3}
set_02 = {1,2,3,4}
set_02.issuperset(set_01)

True

#Dictionaries

Ordered, changeable and indexed

In [ ]:
#dict_01 = dict("a"=1, "b"=2) # Error
dict_01 = dict(a=1, b=2)
dict_01

{'a': 1, 'b': 2}

In [ ]:
#dict_01[0] # error
dict_01["a"]

1

In [ ]:
for i in dict_01:
  print(i)

a
b


In [ ]:
for i in dict_01.items():
  print(i)

('a', 1)
('b', 2)


###Nested Dictionaries


In [ ]:
d_01 = {"a":1}
d_02 = {"b":2}

ndict = {"ndict_1":d_01, "ndict_2":d_02}
ndict

{'ndict_1': {'a': 1}, 'ndict_2': {'b': 2}}

In [ ]:
ndict["ndict_1"]["a"]

1

#Tuples

Immutable

In [ ]:
mytuple = tuple((1,2,3,4))
mytuple

(1, 2, 3, 4)

In [ ]:
mytuple[0]  #Gives error

#Numpy

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])
print(arr,"\n", type(arr))

[1 2 3 4] 
 <class 'numpy.ndarray'>


In [ ]:
lst1 = [1,2,3,4]
lst2 = [5,6,7,8]
lst3 = [9,10,11,12]

arr = np.array([lst1, lst2, lst3])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.shape

(3, 4)

###Indexing

In [ ]:
arr_01 = [1,2,3,4,5,6,7,8]
print(arr_01[:3])
print(arr_01[:-2])
print(arr_01[::-1])
print(arr_01[::-2])

[1, 2, 3]
[1, 2, 3, 4, 5, 6]
[8, 7, 6, 5, 4, 3, 2, 1]
[8, 6, 4, 2]


In [ ]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
arr[-1:,::-3]

array([[12,  9]])

In [ ]:
arr[:, -2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

###For EDA

In [ ]:
earr = np.array([1,2,3,4,5])
earr[earr<4]

array([1, 2, 3])

In [ ]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# To create an array
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.arange(2,20,2).reshape(3,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Numpy Arithmetic

In [ ]:
aarr = np.array([1,2,3])
aarr*aarr

array([1, 4, 9])

In [ ]:
print(np.zeros((2,5)), "\n")
print(np.zeros_like(arr))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
print(np.random.randint(5,15))
print(np.random.randint(5,15,3))

10
[13  5 12]


In [ ]:
np.random.randn(3,3)

array([[ 0.40273332, -0.43872691, -0.15335444],
       [ 0.92237482,  0.17400255,  0.77583673],
       [ 0.50925983, -0.30383189, -0.19284914]])

In [ ]:
np.random.random_sample((2,3)) #Random floats from 0.0-1.0

array([[0.30691848, 0.42566686, 0.92644815],
       [0.24574161, 0.45125847, 0.53369712]])

#Pandas Part 1

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.DataFrame(np.arange(0,12).reshape(4,3), index=["Row1", "Row2", "Row3", "Row4"], columns=["Col1", "Col2", "Col3"])
df

Col1  Col2  Col3
Row1     0     1     2
Row2     3     4     5
Row3     6     7     8
Row4     9    10    11

In [ ]:
#df.head(), df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    4 non-null      int64
 1   Col2    4 non-null      int64
 2   Col13   4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes


In [ ]:
df.describe()  #Uses only the entries which are of int/float types

Col1       Col2       Col3
count  4.000000   4.000000   4.000000
mean   4.500000   5.500000   6.500000
std    3.872983   3.872983   3.872983
min    0.000000   1.000000   2.000000
25%    2.250000   3.250000   4.250000
50%    4.500000   5.500000   6.500000
75%    6.750000   7.750000   8.750000
max    9.000000  10.000000  11.000000

###Indexing

In [ ]:
#Using Columname
print(df["Col1"], "\n")
print(df[['Col1','Col2']])

Row1    0
Row2    3
Row3    6
Row4    9
Name: Col1, dtype: int64 

      Col1  Col2
Row1     0     1
Row2     3     4
Row3     6     7
Row4     9    10


In [ ]:
type(df["Col1"])   #Diff between data frame and series

pandas.core.series.Series

In [ ]:
#Using row index
df.loc[["Row1","Row2"]]

Col1  Col2  Col3
Row1     0     1     2
Row2     3     4     5

In [ ]:
df.iloc[2:,1:]

Col2  Col3
Row3     7     8
Row4    10    11

In [ ]:
#Converting df into arrays
print(df.values, "\n", type(df.values))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 <class 'numpy.ndarray'>


In [ ]:
df_1 = pd.DataFrame((np.array([1,np.nan,3,4,5,6,7,8,9])).reshape(3,3), index=["Row1", "Row2", "Row3"], columns=["Col1", "Col2", "Col3"])
#np.nan
print(df_1)
df_1.isnull().sum()

      Col1  Col2  Col3
Row1   1.0   NaN   3.0
Row2   4.0   5.0   6.0
Row3   7.0   8.0   9.0


Col1    0
Col2    1
Col3    0
dtype: int64

In [ ]:
df_1.isnull()

Col1   Col2   Col3
Row1  False   True  False
Row2  False  False  False
Row3  False  False  False

In [ ]:
df_1['Col2'].value_counts()  # In how many rows that value is present

Col2
5.0    1
8.0    1
Name: count, dtype: int64

In [ ]:
df_1["Col2"].unique()

array([nan,  5.,  8.])

In [ ]:
df_1>2

Col1   Col2  Col3
Row1  False  False  True
Row2   True   True  True
Row3   True   True  True

In [ ]:
df[df["Col1"]>2]   #Important

Col1  Col2  Col3
Row2     3     4     5
Row3     6     7     8
Row4     9    10    11

#Pandas Part 2

In [ ]:
from io import StringIO   # StringIO - in memory file object, has a lot of data | used to convert string data into in memory file format
import pandas as pd

In [ ]:
data = ('1,2,3,4\n'
        'a,b,c,d\n'
        'w,x,y,z')

type(StringIO(data))

_io.StringIO

In [ ]:
df = pd.read_csv(StringIO(data))
df

1  2  3  4
0  a  b  c  d
1  w  x  y  z

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("deepikaravinutala/data-science-projects")

print("Path to dataset files:", path)

100%|██████████| 66.2M/66.2M [00:01<00:00, 55.3MB/s]

Extracting files...


Path to dataset files: /root/.cache/kagglehub/datasets/deepikaravinutala/data-science-projects/versions/1


In [ ]:
df = pd.read_csv('/root/.cache/kagglehub/datasets/deepikaravinutala/data-science-projects/versions/1/Mercedes.csv')
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [ ]:
df2 = pd.read_csv('/root/.cache/kagglehub/datasets/deepikaravinutala/data-science-projects/versions/1/Mercedes.csv', usecols=['y','X0','X1','X2'])
df2.head()

y  X0 X1  X2
0  130.81   k  v  at
1   88.53   k  t  av
2   76.26  az  w   n
3   80.62  az  t   n
4   78.02  az  v   n

In [ ]:
df2.to_csv('test.csv') # Saves the file in the current working dir of the current runtime environment

In [ ]:
#To save the file in drive use
from google.colab import drive
drive.mount('/content/drive')
df2.to_csv('/content/drive/My Drive/test.csv')

In [ ]:
df2.to_csv('test_1.csv', index=False)

###Datatypes in csv

In [ ]:
data = ('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11')

df3 = pd.read_csv(StringIO(data), dtype=object)
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       2 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes


In [ ]:
df3

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [ ]:
df4 = pd.read_csv(StringIO(data), dtype={'a':int, 'b':float, 'c':'object'})
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int64  
 1   b       3 non-null      float64
 2   c       3 non-null      object 
 3   d       2 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 228.0+ bytes


In [ ]:
data = ('index,a,b,c\n'
          '1,2,3,4\n'
          'w,x,y,z')
pd.read_csv(StringIO(data))

index  a  b  c
0     1  2  3  4
1     w  x  y  z

In [ ]:
pd.read_csv(StringIO(data), index_col=0)

a  b  c
index         
1      2  3  4
w      x  y  z

In [ ]:
pd.read_csv(StringIO(data), index_col=2)

index  a  c
b            
3     1  2  4
y     w  x  z

#Pandas Part 3 (working with JSON)

In [ ]:
import pandas as pd

In [ ]:
data = '{"Name ": "James", "email": "james@gmail.com", "Job Profile":[{"Title 1":"Team Lead", "Title 2":"Sr. Developer"}]}'

In [ ]:
pd.read_json(data)

<ipython-input-25-f47fb7e58c56>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data)


Name             email                                        Job Profile
0  James  james@gmail.com  {'Title 1': 'Team Lead', 'Title 2': 'Sr. Devel...

In [ ]:
pd.read_json(data, orient='records')

<ipython-input-26-825f187b7b8e>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data, orient='records')


Name             email                                        Job Profile
0  James  james@gmail.com  {'Title 1': 'Team Lead', 'Title 2': 'Sr. Devel...

In [ ]:
pd.read_json(data, orient='index')

<ipython-input-27-701c1daef8c7>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data, orient='index')


0
Name                                                     James
email                                          james@gmail.com
Job Profile  [{'Title 1': 'Team Lead', 'Title 2': 'Sr. Deve...

In [ ]:
df = pd.DataFrame([['a', 'b'], ['c', 'd']],index=['row 1', 'row 2'],columns=['col1','col2'])

In [ ]:
df

col1 col2
row 1    a    b
row 2    c    d

In [ ]:
df.to_json()

'{"col1":{"row 1":"a","row 2":"c"},"col2":{"row 1":"b","row 2":"d"}}'

In [ ]:
df.to_json(orient='records')

'[{"col1":"a","col2":"b"},{"col1":"c","col2":"d"}]'

In [ ]:
df.to_json(orient='index')

'{"row 1":{"col1":"a","col2":"b"},"row 2":{"col1":"c","col2":"d"}}'

In [ ]:
df.to_json(orient='columns')

'{"col1":{"row 1":"a","row 2":"c"},"col2":{"row 1":"b","row 2":"d"}}'

In [ ]:
df.to_json(orient='split')

'{"columns":["col1","col2"],"index":["row 1","row 2"],"data":[["a","b"],["c","d"]]}'

In [ ]:
schema = df.to_json(orient='table')
schema

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col1","type":"string"},{"name":"col2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row 1","col1":"a","col2":"b"},{"index":"row 2","col1":"c","col2":"d"}]}'

In [ ]:
pd.read_json(schema, orient='table')

<ipython-input-36-00b1a0136d4d>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(schema, orient='table')


col1 col2
row 1    a    b
row 2    c    d

In [ ]:
data = [{"Name ": "James", "email": "james@gmail.com", "Job Profile":{"Title 1":"Team Lead", "Title 2":"Sr. Developer"}}]
pd.json_normalize(data)

Name             email Job Profile.Title 1 Job Profile.Title 2
0  James  james@gmail.com           Team Lead       Sr. Developer

In [ ]:
data = [
{
"id": 1,
"name": "Cole Volk",
"fitness": {"height": 130, "weight": 60},
},

{"name": "Mark Reg", "fitness": {"height": 130, "weight": 60}},
{
"id": 2,
"name": "Faye Raker",
"fitness": {"height": 130, "weight":60},
},
]

In [ ]:
pd.json_normalize(data)

id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mark Reg             130              60
2  2.0  Faye Raker             130              60

In [ ]:
pd.json_normalize(data, max_level=0)

id        name                        fitness
0  1.0   Cole Volk  {'height': 130, 'weight': 60}
1  NaN    Mark Reg  {'height': 130, 'weight': 60}
2  2.0  Faye Raker  {'height': 130, 'weight': 60}

In [ ]:
data = [

{

"state": "Florida",
"shortname": "FL",
"info": {"governor": "Rick Scott"},

"counties":[
  {"name": "Dade", "population": 12345},
  {"name": "Broward", "population": 40000},
  {"name": "Palm Beach", "population": 60000},

],

},
{
  "state": "Ohio",
  "shortname": "OH",
  "info": {"governor": "John Kasich"},
  "counties":[
    {"name": "Summit", "population": 1234},
    {"name": "Cuyahoga", "population": 1337},
  ],
  },
]

In [ ]:
pd.json_normalize(data)

state shortname                                           counties  \
0  Florida        FL  [{'name': 'Dade', 'population': 12345}, {'name...   
1     Ohio        OH  [{'name': 'Summit', 'population': 1234}, {'nam...   

  info.governor  
0    Rick Scott  
1   John Kasich

In [ ]:
pd.json_normalize(data, "counties")

name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [ ]:
pd.json_normalize(data, "counties", ["state","shortname","info"])

name  population    state shortname                         info
0        Dade       12345  Florida        FL   {'governor': 'Rick Scott'}
1     Broward       40000  Florida        FL   {'governor': 'Rick Scott'}
2  Palm Beach       60000  Florida        FL   {'governor': 'Rick Scott'}
3      Summit        1234     Ohio        OH  {'governor': 'John Kasich'}
4    Cuyahoga        1337     Ohio        OH  {'governor': 'John Kasich'}

In [ ]:
pd.json_normalize(data, "counties", ["state","shortname",["info","governor"]])

name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

#Pandas with HTML (Part 4)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_html("https://en.wikipedia.org/wiki/Economy_of_the_United_States")
df

[                                                    0  \
 0   New York City, the world's principal fintech a...   
 1                                            Currency   
 2                                         Fiscal year   
 3                                 Trade organizations   
 4                                       Country group   
 5                                          Statistics   
 6                                          Population   
 7                                                 GDP   
 8                                            GDP rank   
 9                                          GDP growth   
 10                                     GDP per capita   
 11                                GDP per capita rank   
 12                                      GDP by sector   
 13                                   GDP by component   
 14                                    Inflation (CPI)   
 15                      Population below poverty line   
 16           

In [ ]:
type(df)

list

In [ ]:
df[1]

0
0            This article is part of a series on the
1                       Economy of the United States
2  Economic history Agricultural history Banking ...
3  Sectors Primary sector Agriculture Energy Petr...
4  Economy by state California Texas New York Flo...
5  Economy by city or county Allentown Atlanta Bu...
6  Labor Labor Law Child labor Labor unions Minim...
7                               United States portal
8                                                vte

In [ ]:
type(df[1])

pandas.core.frame.DataFrame

In [ ]:
html = pd.read_html("https://en.wikipedia.org/wiki/New_York_City#Boroughs", match="Historical population")
html = pd.DataFrame(html[0])
html

Year     Pop.       ±%
0        1698     4937        —
1        1712     5840   +18.3%
2        1723     7248   +24.1%
3        1737    10664   +47.1%
4        1746    11717    +9.9%
5        1756    13046   +11.3%
6        1771    21863   +67.6%
7        1790    33131   +51.5%
8        1800    60515   +82.7%
9        1810    96373   +59.3%
10       1820   123706   +28.4%
11       1830   202589   +63.8%
12       1840   312710   +54.4%
13       1850   515547   +64.9%
14       1860   813669   +57.8%
15       1870   942292   +15.8%
16       1880  1206299   +28.0%
17       1890  1515301   +25.6%
18       1900  3437202  +126.8%
19       1910  4766883   +38.7%
20       1920  5620048   +17.9%
21       1930  6930446   +23.3%
22       1940  7454995    +7.6%
23       1950  7891957    +5.9%
24       1960  7781984    −1.4%
25       1970  7894862    +1.5%
26       1980  7071639   −10.4%
27       1990  7322564    +3.5%
28       2000  8008288    +9.4%
29       2010  8175133    +2.1%
30       2020  8804190    +7.7%
31  2023 est.  8258035    −6.2%
32        [e]      [e]      [e]

In [ ]:
type(html)

pandas.core.frame.DataFrame

In [ ]:
html.to_html("demo.html")

#Pandas with XML

In [ ]:
xml = '''<data>
  <row>
    <column1>A</column1>
    <column2>1</column2>
  </row>
  <row>
    <column1>B</column1>
    <column2>2</column2>
  </row>
  <row>
    <column1>C</column1>
    <column2/>
  </row>
</data>
'''
pd.read_xml(xml)

<ipython-input-76-8427179693e3>:16: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml)


column1  column2
0       A      1.0
1       B      2.0
2       C      NaN

In [ ]:
xml2 = '''<data>
  <row column1="A" column2="1"/>
  <row column1="B" column2="2"/>
  <row column1="C" column2=""/>
</data>
'''
pd.read_xml(xml2)

<ipython-input-84-9339f1ee298a>:7: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml2)


column1  column2
0       A      1.0
1       B      2.0
2       C      NaN

In [ ]:
pd.read_xml(xml2, xpath=".//row")  #Specifies that 'row' is the tag name

<ipython-input-85-0de56b114b3c>:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml2, xpath=".//row")  #Specifies that 'row' is the tag name


column1  column2
0       A      1.0
1       B      2.0
2       C      NaN

In [ ]:
xml3 = '''<products xmlns:prd="http://www.example.com/products">
  <prd:product>
    <prd:name>Laptop</prd:name>
    <prd:price>1200</prd:price>
    <prd:category>Electronics</prd:category>
  </prd:product>
  <prd:product>
    <prd:name>Phone</prd:name>
    <prd:price>800</prd:price>
    <prd:category>Electronics</prd:category>
  </prd:product>
  <prd:product>
    <prd:name>Table</prd:name>
    <prd:price>300</prd:price>
    <prd:category>Furniture</prd:category>
  </prd:product>
  <prd:product>
    <prd:name>Chair</prd:name>
    <prd:price>150</prd:price>
    <prd:category>Furniture</prd:category>
  </prd:product>
</products>
'''

In [ ]:
df = pd.read_xml(xml3, xpath=".//prd:product", namespaces={"prd": "http://www.example.com/products"})
df

<ipython-input-88-5e4421a7d42b>:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_xml(xml3, xpath=".//prd:product", namespaces={"prd": "http://www.example.com/products"})


name  price     category
0  Laptop   1200  Electronics
1   Phone    800  Electronics
2   Table    300    Furniture
3   Chair    150    Furniture

#Pickling and Unpickling

Pickle in Python is primarily used in serializing and deserializing a Python object structure. In other words, it's the process of converting a Python object into a byte stream to store it in a file/database, maintain program state across sessions, or transport data over the network

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
import pickle

In [ ]:
filename = "file.pkl"

In [ ]:
#Serialize process
pickle.dump(df, open(filename, "wb"))

In [ ]:
#Unserialize process
pickle.load(open(filename, "rb"))

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

#Functions in Python

In [ ]:
def welcome()
  """
  Description: This function will show a welcome message

  Return Type: This function will return the welcome message
  """
  return "Hello"

welcome()

In [ ]:
def hello(name, age = 21):   #Keyword value
  print("Hello "+ name + ", you are " + str(age) + " years old.")

hello("Anirudh")
hello("Anirudh", 32)   # Positional value

Hello Anirudh, you are 21 years old.
Hello Anirudh, you are 32 years old.


In [ ]:
def Hello(*args, **kwargs):
  print(args)
  print(kwargs)

Hello('Anirudh','Singh',age=21, dob=2003)

lst=['Anirudh','Singh']
dict_args={'age':21, 'dob':2003}
print("\n")

Hello(lst, dict_args)
print("\n")

Hello(*lst, **dict_args)

('Anirudh', 'Singh')
{'age': 21, 'dob': 2003}


(['Anirudh', 'Singh'], {'age': 21, 'dob': 2003})
{}


('Anirudh', 'Singh')
{'age': 21, 'dob': 2003}


*To define the return type of a function - <br> def f(params) -> data_type


#OOPS

In [1]:
#Classes - real world entity or object
class Car:
  pass

car1=Car()
car2=Car()

car1.windows=4
car1.tyres=4

car2.windows=6
car2.tyres=6
car2.engine="Petrol"

print(car1.windows)
print(car2.engine)
dir(Car)

4
Petrol


['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [ ]:
class Car():
  def __init__(self, window, tyres, engine):
    self.windows=window
    self.tyres=tyres
    self.engine=engine

  def self__driving(self):
    print("This car has a {} engine".format(self.engine))

  def self__driving_2(self,engine):
    print("This car has a {} engine".format(engine))

car1=Car(4,4,"Petrol")
car1.self__driving()
#car1.self__driving("Electric")        #Error
car1.self__driving_2("Electric")

This car has a Petrol engine
This car has a Electric engine


In [ ]:
class Animal:
  def __init__(self, name, species):
    self.name = name
    self.species = species
  def __init__(self, name, species,age):
    self.name = name
    self.species = species
    self.age = age

  def make_sound(sound):
    print(f"{self.name} the {self.species} says {sound}")

#dog = Animal("dog", "mammals")   #Error because of constructor overrinding


In [ ]:
#To fix this -
class Animal:
  def __init__(self, *args):
    if len(args) == 1:
      self.name = args[0]
    elif len(args) == 2:
      self.name = args[0]
      self.species = args[1]
    else:
      self.name = args[0]
      self.species = args[1]
      self.age = args[2]

dog = Animal("dog", "mammals")
chicken = Animal("chicken", "bird", 2)
print(dog.name, dog.species)
print(chicken.name, chicken.species, chicken.age)

dog mammals
chicken bird 2


##Inheritance

In [ ]:
class Car():
  def __init__(self, window, tyres, engine):
    self.windows=window
    self.tyres=tyres
    self.engine=engine

  def self__driving(self):
    print("This car has a {} engine".format(self.engine))

class Audi(Car):
  def __init__(self, window, tyres, engine, horsepower):
    super().__init__(window, tyres, engine)
    self.horsepower=horsepower;

  def self__driving(self):
    print("The car is self driving")


#List Comprehension

In [ ]:
lst1=[1,2,3,4,5,6,7,8,9,10]
lst2=[i**2 for i in lst1]
lst2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
lst3 = [i for i in lst1 if i%2==0]
lst3

[2, 4, 6, 8, 10]

In [ ]:
#Flattening a list
lists = [[1,2,3],[4,5,6],[7,8,9]]
flat_list = [item for sublist in lists for item in sublist]
flat_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
words = ["apple", "banana", "cherry", "date", "elderberry"]
letters = [word[0] for word in words ]
letters

['a', 'b', 'c', 'd', 'e']

In [ ]:
# Fibonacci Series
[lst1[i-2]+lst1[i-1] for i in range(2,len(lst1)+1)]

[3, 5, 7, 9, 11, 13, 15, 17, 19]

#Lambda Function

In [ ]:
add = lambda x,y : x+y
add(4,5)

9

In [ ]:
str_len = lambda s: len(s)
str_len("Anirudh")

7

In [ ]:
# Converting a list of nos to squares
nos = [1,2,3,4,5]
sqred_lst = list(map(lambda x:x**2,nos))
print(sqred_lst)

TypeError: 'list' object is not callable

In [ ]:
#Filter out even nos
nos = [1,2,3,4,5,6,7,8,9,10]
even_nos = list(filter(lambda x:x%2==0,nos))
print(even_nos)

TypeError: 'list' object is not callable

In [ ]:
# Sorting a lsit of strings based on their alphabetical order and length
words = ["apple", "banana", "cherry", "date", "elderberry"]
sorted(words, key=lambda x:len(x))

['date', 'apple', 'banana', 'cherry', 'elderberry']

In [ ]:
people = [
    {'name': 'Alice', 'age': 25, 'occupation': 'Engineer'},
    {'name': 'Bob', 'age': 30, 'occupation': 'Manager'},
    {'name': 'Charlie', 'age': 22, 'occupation': 'Intern'},
    {'name': 'Dave', 'age': 27, 'occupation': 'Designer'},
]

sorted(people, key=lambda x:x['name'])

[{'name': 'Alice', 'age': 25, 'occupation': 'Engineer'},
 {'name': 'Bob', 'age': 30, 'occupation': 'Manager'},
 {'name': 'Charlie', 'age': 22, 'occupation': 'Intern'},
 {'name': 'Dave', 'age': 27, 'occupation': 'Designer'}]

In [ ]:
sorted(people, key=lambda x:(['age'],x['name']))

[{'name': 'Alice', 'age': 25, 'occupation': 'Engineer'},
 {'name': 'Bob', 'age': 30, 'occupation': 'Manager'},
 {'name': 'Charlie', 'age': 22, 'occupation': 'Intern'},
 {'name': 'Dave', 'age': 27, 'occupation': 'Designer'}]

In [ ]:
#Find the max value in a dictionary
dict = {'a': 10, 'b': 5, 'c': 20, 'd': 15}
max(dict, key=lambda x: dict[x])

'c'

#Dataclass

In [ ]:
from dataclasses import dataclass

In [ ]:
@dataclass
class Car:
  mileage: float
  automatic: bool
  color: str = 'White'

In [ ]:
@dataclass(frozen=True)  # Using this x attributes of Point cannot be changed
class Point:
  x:int
  y:int

In [ ]:
#Inheritance
@dataclass
class Person:
  name: str
  age: int

@dataclass
class Student(Person):
  student_id: str

S1 = Student("Anirudh",21,"074")

In [ ]:
#ensted dataclasses
@dataclass
class Address:
  street: str
  city: str

@dataclass
class Person:
  name: str
  age: int
  address: Address

address = Address("123 Main St", "New York")
person = Person("John Doe", 30, address)
person.address

Address(street='123 Main St', city='New York')

#Encapsulation

Private - variables and methods can only be used in the same class <br>
Protected - variables and methods can only be used in the derived classed <br>
Public - variables and methods can be used anywhere

In [ ]:
class Car:
    def __init__(self, color):
        self.color = color  # Public attribute

    def start(self):
        print("Car started.")

my_car = Car("Red")
print(my_car.color)  # Accessing public attribute
my_car.start()

In [ ]:
class Car:
    def __init__(self, color):
        self.__color = color  # Private attribute

    def get_color(self):
        return self.__color

my_car = Car("Blue")
# print(my_car.__color)  # Direct access (usually discouraged)
print(my_car.get_color())  # Accessing through a public method

In [ ]:
class Vehicle:
    def __init__(self, max_speed):
        self._max_speed = max_speed  # Protected attribute

class Car(Vehicle):
    def __init__(self, color, max_speed):
        super().__init__(max_speed)
        self.color = color

    def get_max_speed(self):
        return self._max_speed

my_car = Car("Red", 180)
print(my_car.get_max_speed())